server:
  port: 8080
spring:
  application:
      name: proxy-server
eureka:
  instance:
    referIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: {EUREKA_URI:http://localhost:8761/eureka}